import JSZip from 'jszip'
import type { Episode, Show } from '@/types/database'
import type { GuestPackageContent } from '@/lib/guest-package/generator'

/**
 * ZIP export service for guest packages
 * Generates downloadable ZIP files with organized content structure
 */

export interface GenerateZipParams {
  episode: Episode
  show: Show
  packageContent: GuestPackageContent
}

/**
 * Shared ZIP creation logic - builds ZIP structure with all files
 */
function createZipStructure(params: GenerateZipParams): JSZip {
  const { episode, show, packageContent } = params
  const zip = new JSZip()

  // Create folder structure
  const socialPostsFolder = zip.folder('social-posts')
  const quotesFolder = zip.folder('quotes')

  if (!socialPostsFolder || !quotesFolder) {
    throw new Error('Failed to create ZIP folder structure')
  }

  // Add social media posts
  packageContent.socialPosts.forEach((post) => {
    const filename = `${post.platform}.txt`
    const content = [
      `${post.platform.toUpperCase()} POST`,
      `Character Count: ${post.characterCount} / ${post.maxCharacters}`,
      '',
      post.content,
      '',
      '---',
      `Generated by PodBrain for ${show.name}`,
      `Episode: ${episode.title || 'Untitled Episode'}`,
    ].join('\n')

    socialPostsFolder.file(filename, content)
  })

  // Add quote cards
  packageContent.quoteCards.forEach((quote, index) => {
    const filename = `quote-${index + 1}.txt`
    const content = [
      `QUOTE CARD ${index + 1}`,
      '',
      `"${quote.quote}"`,
      '',
      `— ${quote.attribution}`,
      `${quote.episodeTitle}`,
      '',
      '---',
      'Note: This is a text version. Generate visual quote cards using design tools.',
    ].join('\n')

    quotesFolder.file(filename, content)
  })

  // Add email template
  const emailContent = [
    'EMAIL TEMPLATE',
    '',
    `Subject: ${packageContent.emailSubject}`,
    '',
    'Body:',
    packageContent.emailBody,
  ].join('\n')

  zip.file('email-template.txt', emailContent)

  // Add README with instructions
  const readmeContent = [
    'GUEST PROMOTION PACKAGE',
    '='.repeat(60),
    '',
    `Episode: ${episode.title || 'Untitled Episode'}`,
    `Guest: ${episode.guest_name || 'Guest'}`,
    `Show: ${show.name}`,
    `Generated: ${new Date().toLocaleDateString()}`,
    '',
    '='.repeat(60),
    '',
    'CONTENTS:',
    '',
    '1. /social-posts/ - Ready-to-use posts for LinkedIn, Twitter, and Instagram',
    '   - Each file contains formatted text optimized for the platform',
    '   - Character counts are included for reference',
    '   - Feel free to customize before posting',
    '',
    '2. /quotes/ - Memorable quotes from your episode',
    '   - Text versions of quotable moments',
    '   - Use these to create visual quote cards with tools like Canva',
    '   - Great for social media and blog posts',
    '',
    '3. email-template.txt - Email template for your subscribers',
    '   - Announce your podcast appearance',
    '   - Customize with your voice and branding',
    '',
    '='.repeat(60),
    '',
    'HOW TO USE THIS PACKAGE:',
    '',
    '1. Review all content and customize to match your voice',
    '2. Post to social media (tag the show for maximum reach)',
    '3. Share with your email list',
    '4. Create visual quote cards using design tools',
    '5. Thank the show host and team in your posts',
    '',
    '='.repeat(60),
    '',
    'TIPS FOR MAXIMUM REACH:',
    '',
    '- Post within 24-48 hours of episode release for best engagement',
    '- Tag the show\'s social media accounts',
    '- Use relevant hashtags for your industry',
    '- Share across multiple platforms',
    '- Engage with comments and shares',
    '- Pin the post to your profile for a few days',
    '',
    '='.repeat(60),
    '',
    `Generated by PodBrain - ${new Date().toISOString()}`,
    'Questions? Visit getpodbrain.ai',
  ].join('\n')

  zip.file('README.txt', readmeContent)

  return zip
}

/**
 * Generate guest package ZIP for client-side download (returns Blob)
 */
export async function generateGuestPackageZip(params: GenerateZipParams): Promise<Blob> {
  const zip = createZipStructure(params)

  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}

/**
 * Generate guest package ZIP for server-side (returns Buffer for Node.js)
 */
export async function generateGuestPackageZipServer(params: GenerateZipParams): Promise<Buffer> {
  const zip = createZipStructure(params)

  return await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}

/**
 * Asset for bulk download
 */
export interface AssetForDownload {
  id: string
  type: string
  name: string
  category: string
  content: string
}

export interface GenerateAssetsZipParams {
  episodeTitle: string
  showName: string
  assets: AssetForDownload[]
}

/**
 * Create ZIP structure for content assets
 */
function createAssetsZipStructure(params: GenerateAssetsZipParams): JSZip {
  const { episodeTitle, showName, assets } = params
  const zip = new JSZip()

  // Group assets by category
  const assetsByCategory = assets.reduce((acc, asset) => {
    const category = asset.category || 'other'
    if (!acc[category]) {
      acc[category] = []
    }
    acc[category].push(asset)
    return acc
  }, {} as Record<string, AssetForDownload[]>)

  // Create folders for each category and add assets
  Object.entries(assetsByCategory).forEach(([category, categoryAssets]) => {
    const folder = zip.folder(category)
    if (!folder) return

    categoryAssets.forEach((asset, index) => {
      // Sanitize filename
      const safeName = asset.name.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase()
      const filename = `${safeName}.txt`

      // Format content based on type
      let formattedContent = asset.content

      // Try to parse JSON content (for threads, quotes, etc.)
      try {
        const parsed = JSON.parse(asset.content)
        if (Array.isArray(parsed)) {
          formattedContent = parsed.map((item, i) => {
            if (typeof item === 'string') {
              return `${i + 1}. ${item}`
            }
            if (item.quote) {
              return `"${item.quote}"\n— ${item.speaker || 'Unknown'}\n${item.timestamp ? `(${item.timestamp})` : ''}`
            }
            return JSON.stringify(item, null, 2)
          }).join('\n\n---\n\n')
        } else if (typeof parsed === 'object') {
          formattedContent = JSON.stringify(parsed, null, 2)
        }
      } catch {
        // Not JSON, use as-is
      }

      const content = [
        `${asset.name.toUpperCase()}`,
        '='.repeat(60),
        '',
        formattedContent,
        '',
        '---',
        `Asset Type: ${asset.type}`,
        `Category: ${category}`,
        `Generated by PodBrain`,
      ].join('\n')

      folder.file(filename, content)
    })
  })

  // Add README
  const readme = [
    'CONTENT ASSETS PACKAGE',
    '='.repeat(60),
    '',
    `Episode: ${episodeTitle}`,
    `Show: ${showName}`,
    `Generated: ${new Date().toLocaleDateString()}`,
    `Total Assets: ${assets.length}`,
    '',
    '='.repeat(60),
    '',
    'FOLDER STRUCTURE:',
    '',
    ...Object.entries(assetsByCategory).map(([category, categoryAssets]) =>
      `/${category}/ - ${categoryAssets.length} asset(s)`
    ),
    '',
    '='.repeat(60),
    '',
    'HOW TO USE THESE ASSETS:',
    '',
    '1. Review and customize each asset to match your voice',
    '2. Copy/paste into your social media platforms',
    '3. Schedule posts for consistent engagement',
    '4. Track which formats perform best',
    '',
    '='.repeat(60),
    '',
    `Generated by PodBrain - ${new Date().toISOString()}`,
    'Visit getpodbrain.ai for more',
  ].join('\n')

  zip.file('README.txt', readme)

  return zip
}

/**
 * Generate assets ZIP for client-side download (returns Blob)
 */
export async function generateAssetsZip(params: GenerateAssetsZipParams): Promise<Blob> {
  const zip = createAssetsZipStructure(params)

  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}

/**
 * Generate assets ZIP for server-side (returns Buffer)
 */
export async function generateAssetsZipServer(params: GenerateAssetsZipParams): Promise<Buffer> {
  const zip = createAssetsZipStructure(params)

  return await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}
