import JSZip from 'jszip'
import type { Episode, Show } from '@/types/database'
import type { GuestPackageContent } from '@/lib/guest-package/generator'

/**
 * ZIP export service for guest packages
 * Generates downloadable ZIP files with organized content structure
 */

export interface GenerateZipParams {
  episode: Episode
  show: Show
  packageContent: GuestPackageContent
}

/**
 * Shared ZIP creation logic - builds ZIP structure with all files
 */
function createZipStructure(params: GenerateZipParams): JSZip {
  const { episode, show, packageContent } = params
  const zip = new JSZip()

  // Create folder structure
  const socialPostsFolder = zip.folder('social-posts')
  const quotesFolder = zip.folder('quotes')

  if (!socialPostsFolder || !quotesFolder) {
    throw new Error('Failed to create ZIP folder structure')
  }

  // Add social media posts
  packageContent.socialPosts.forEach((post) => {
    const filename = `${post.platform}.txt`
    const content = [
      `${post.platform.toUpperCase()} POST`,
      `Character Count: ${post.characterCount} / ${post.maxCharacters}`,
      '',
      post.content,
      '',
      '---',
      `Generated by PodBrain for ${show.name}`,
      `Episode: ${episode.title || 'Untitled Episode'}`,
    ].join('\n')

    socialPostsFolder.file(filename, content)
  })

  // Add quote cards
  packageContent.quoteCards.forEach((quote, index) => {
    const filename = `quote-${index + 1}.txt`
    const content = [
      `QUOTE CARD ${index + 1}`,
      '',
      `"${quote.quote}"`,
      '',
      `— ${quote.attribution}`,
      `${quote.episodeTitle}`,
      '',
      '---',
      'Note: This is a text version. Generate visual quote cards using design tools.',
    ].join('\n')

    quotesFolder.file(filename, content)
  })

  // Add email template
  const emailContent = [
    'EMAIL TEMPLATE',
    '',
    `Subject: ${packageContent.emailSubject}`,
    '',
    'Body:',
    packageContent.emailBody,
  ].join('\n')

  zip.file('email-template.txt', emailContent)

  // Add README with instructions
  const readmeContent = [
    'GUEST PROMOTION PACKAGE',
    '='.repeat(60),
    '',
    `Episode: ${episode.title || 'Untitled Episode'}`,
    `Guest: ${episode.guest_name || 'Guest'}`,
    `Show: ${show.name}`,
    `Generated: ${new Date().toLocaleDateString()}`,
    '',
    '='.repeat(60),
    '',
    'CONTENTS:',
    '',
    '1. /social-posts/ - Ready-to-use posts for LinkedIn, Twitter, and Instagram',
    '   - Each file contains formatted text optimized for the platform',
    '   - Character counts are included for reference',
    '   - Feel free to customize before posting',
    '',
    '2. /quotes/ - Memorable quotes from your episode',
    '   - Text versions of quotable moments',
    '   - Use these to create visual quote cards with tools like Canva',
    '   - Great for social media and blog posts',
    '',
    '3. email-template.txt - Email template for your subscribers',
    '   - Announce your podcast appearance',
    '   - Customize with your voice and branding',
    '',
    '='.repeat(60),
    '',
    'HOW TO USE THIS PACKAGE:',
    '',
    '1. Review all content and customize to match your voice',
    '2. Post to social media (tag the show for maximum reach)',
    '3. Share with your email list',
    '4. Create visual quote cards using design tools',
    '5. Thank the show host and team in your posts',
    '',
    '='.repeat(60),
    '',
    'TIPS FOR MAXIMUM REACH:',
    '',
    '- Post within 24-48 hours of episode release for best engagement',
    '- Tag the show\'s social media accounts',
    '- Use relevant hashtags for your industry',
    '- Share across multiple platforms',
    '- Engage with comments and shares',
    '- Pin the post to your profile for a few days',
    '',
    '='.repeat(60),
    '',
    `Generated by PodBrain - ${new Date().toISOString()}`,
    'Questions? Visit getpodbrain.ai',
  ].join('\n')

  zip.file('README.txt', readmeContent)

  return zip
}

/**
 * Generate guest package ZIP for client-side download (returns Blob)
 */
export async function generateGuestPackageZip(params: GenerateZipParams): Promise<Blob> {
  const zip = createZipStructure(params)

  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}

/**
 * Generate guest package ZIP for server-side (returns Buffer for Node.js)
 */
export async function generateGuestPackageZipServer(params: GenerateZipParams): Promise<Buffer> {
  const zip = createZipStructure(params)

  return await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })
}
