// @vitest-environment node
/**
 * Phase C: Output Quality Verification with Grok-as-Judge
 *
 * After the pipeline test generates content, this suite evaluates the QUALITY
 * of every generated asset using a dual verification approach:
 *
 *   1. Grok-as-judge: xAI Grok evaluates each asset for relevance, accuracy,
 *      formatting, and usefulness (scored 1-10)
 *   2. Manual double-check: Programmatic assertions verify keyword overlap,
 *      hallucination detection, and platform character limits
 *
 * This suite reads assets from the database that were generated by pipeline.test.ts.
 * If no assets exist, it generates a small set for testing.
 *
 * Expected runtime: ~3-5 minutes (one Grok call per asset type for judging)
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { ensureLiveTestUser, getAdminClient } from './helpers/auth';
import { getEpisode, fetchAllAssets, createTestShow, uploadAndCreateEpisode, transcribeEpisode, generateShowNotes, CORE_ASSET_TYPES } from './helpers/pipeline';
import {
  evaluateWithGrok,
  evaluateAssetBatch,
  assertContentRelevance,
  assertNoHallucinations,
  assertPlatformLimits,
  printQualityReport,
} from './helpers/quality-judge';

// We'll look for assets from the pipeline test, or generate a minimal set
let episodeId: string;
let transcript: string;
let showName: string;
let guestName: string | undefined;
let assets: Array<{ asset_type: string; content: string; metadata: unknown }> = [];

describe('Quality Verification: Grok-as-Judge + Manual Checks', () => {
  beforeAll(async () => {
    console.log('\n--- Quality Test Setup ---');
    await ensureLiveTestUser();
    const admin = getAdminClient();

    // Find the most recent live-test episode that has assets
    const { data: episodes } = await admin
      .from('episodes')
      .select('id, title, transcript, show_notes, guest_name, shows(name)')
      .ilike('title', '%LIVE-TEST%')
      .not('transcript', 'is', null)
      .order('created_at', { ascending: false })
      .limit(1);

    if (episodes && episodes.length > 0) {
      const ep = episodes[0];
      episodeId = ep.id;
      transcript = ep.transcript!;
      guestName = ep.guest_name || undefined;
      const showData = Array.isArray(ep.shows) ? ep.shows[0] : ep.shows;
      showName = (showData as { name: string })?.name || 'Test Show';

      // Fetch assets
      const dbAssets = await fetchAllAssets(episodeId);
      if (dbAssets.length > 0) {
        assets = dbAssets;
        console.log(`  Found ${assets.length} assets from pipeline test (episode: ${episodeId})`);
      }
    }

    // If no assets found, generate a minimal set for quality testing
    if (assets.length === 0) {
      console.log('  No existing assets found — generating a minimal set...');

      const show = await createTestShow('[LIVE-TEST] Quality Test Show');
      showName = show.name;

      const result = await uploadAndCreateEpisode(show.id, '[LIVE-TEST] Quality Test Episode', 'Test Guest');
      episodeId = result.episodeId;
      guestName = 'Test Guest';

      const transcription = await transcribeEpisode(episodeId, result.audioUrl);
      transcript = transcription.text;

      const showNotes = await generateShowNotes(episodeId);
      if (showNotes) {
        assets.push({ asset_type: 'show_notes', content: showNotes, metadata: {} });
      }

      // Generate a few key assets directly
      const { generateAsset, buildAssetContext, formatAssetForStorage } = await import('@/lib/content');
      const episode = await getEpisode(episodeId);
      const epShowData = Array.isArray(episode.shows) ? episode.shows[0] : episode.shows;
      const context = buildAssetContext(episode, epShowData?.name || showName, { guestName });

      const minimalTypes = [
        'key_takeaways', 'blog_post', 'linkedin_post', 'twitter_thread',
        'seo_description', 'guest_bio_short', 'transcript_summary',
      ] as const;

      for (const assetType of minimalTypes) {
        const genResult = await generateAsset(assetType, context);
        if (genResult.success) {
          const formatted = formatAssetForStorage(episodeId, genResult);
          await admin.from('generated_assets').insert(formatted);
          assets.push({ asset_type: assetType, content: formatted.content, metadata: formatted.metadata });
        }
        await new Promise(r => setTimeout(r, 300));
      }

      console.log(`  Generated ${assets.length} assets for quality testing`);
    }

    expect(assets.length).toBeGreaterThan(0);
    expect(transcript).toBeTruthy();
  }, 600_000); // 10 min timeout for potential asset generation

  // ─── Grok-as-Judge Evaluation ──────────────────────────────────────
  describe('Grok-as-Judge: AI Quality Evaluation', () => {
    it('should achieve >= 80% pass rate across all evaluated assets', async () => {
      const assetsToEvaluate = assets
        .filter(a => a.content && a.content.length > 10)
        .map(a => ({ type: a.asset_type, content: a.content }));

      console.log(`\n  Evaluating ${assetsToEvaluate.length} assets with Grok-as-judge...\n`);

      const report = await evaluateAssetBatch(
        transcript,
        showName,
        assetsToEvaluate,
        guestName
      );

      // Print the quality report
      printQualityReport(report.results);

      // Check pass rate
      console.log(`  Pass rate: ${(report.passRate * 100).toFixed(0)}%`);
      console.log(`  Average score: ${report.averageScore.toFixed(1)}/10`);

      if (report.failures.length > 0) {
        console.warn(`  Failures:`);
        for (const f of report.failures) {
          console.warn(`    - ${f}`);
        }
      }

      // At least 70% of assets should score 6+/10
      // (Threshold is lower because our test audio is a ~30 second clip,
      // so the generated content has limited source material to work with)
      expect(report.passRate).toBeGreaterThanOrEqual(0.7);
      expect(report.averageScore).toBeGreaterThanOrEqual(5.0);
    }, 300_000); // 5 min for all evaluations
  });

  // ─── Manual Double-Check: Content Relevance ────────────────────────
  describe('Manual Check: Content Relevance', () => {
    it('should verify keyword overlap between transcript and each asset', () => {
      let passCount = 0;
      let totalChecked = 0;

      for (const asset of assets) {
        if (!asset.content || asset.content.length < 20) continue;
        totalChecked++;

        const result = assertContentRelevance(asset.content, transcript, 2);

        if (result.passed) {
          passCount++;
        } else {
          console.warn(`  Low keyword overlap for ${asset.asset_type}: ${result.matchedKeywords.join(', ')}`);
        }
      }

      const passRate = totalChecked > 0 ? passCount / totalChecked : 0;
      console.log(`\n  Keyword relevance: ${passCount}/${totalChecked} passed (${(passRate * 100).toFixed(0)}%)`);

      // At least 90% should have meaningful keyword overlap
      expect(passRate).toBeGreaterThanOrEqual(0.9);
    });
  });

  // ─── Manual Double-Check: Hallucination Detection ──────────────────
  describe('Manual Check: Hallucination Detection', () => {
    it('should detect minimal hallucinated proper nouns', () => {
      let passCount = 0;
      let totalChecked = 0;
      const allSuspicious: Record<string, string[]> = {};

      for (const asset of assets) {
        if (!asset.content || asset.content.length < 30) continue;
        totalChecked++;

        const result = assertNoHallucinations(asset.content, transcript);

        if (result.passed) {
          passCount++;
        } else {
          allSuspicious[asset.asset_type] = result.suspiciousTerms;
        }
      }

      if (Object.keys(allSuspicious).length > 0) {
        console.warn('\n  Potential hallucinations detected:');
        for (const [type, terms] of Object.entries(allSuspicious)) {
          console.warn(`    ${type}: ${terms.join(', ')}`);
        }
      }

      const passRate = totalChecked > 0 ? passCount / totalChecked : 0;
      console.log(`\n  Hallucination check: ${passCount}/${totalChecked} passed (${(passRate * 100).toFixed(0)}%)`);

      // Allow some leeway — AI may use common proper nouns not in transcript
      expect(passRate).toBeGreaterThanOrEqual(0.7);
    });
  });

  // ─── Manual Double-Check: Platform Character Limits ────────────────
  describe('Manual Check: Platform Character Limits', () => {
    it('should verify platform-specific character limits', () => {
      const platformAssets = assets.filter(a =>
        ['twitter_single', 'instagram_caption', 'seo_description', 'tiktok_hooks'].includes(a.asset_type)
      );

      let passCount = 0;
      const issues: string[] = [];

      for (const asset of platformAssets) {
        // For JSON array types (twitter_single, tiktok_hooks), check individual items
        let content = asset.content;
        try {
          const parsed = JSON.parse(content);
          if (Array.isArray(parsed)) {
            // Check each item individually for twitter
            if (asset.asset_type === 'twitter_single') {
              let allPass = true;
              for (const item of parsed) {
                const text = typeof item === 'string' ? item : item?.text;
                if (typeof text === 'string') {
                  const result = assertPlatformLimits(asset.asset_type, text);
                  if (!result.passed) {
                    issues.push(result.issue!);
                    allPass = false;
                  }
                }
              }
              if (allPass) passCount++;
              continue;
            }
            // For other arrays, check the first item
            content = typeof parsed[0] === 'string' ? parsed[0] : JSON.stringify(parsed[0]);
          } else if (typeof parsed === 'object' && parsed.content) {
            content = parsed.content;
          }
        } catch {
          // Not JSON, use as-is
        }

        const result = assertPlatformLimits(asset.asset_type, content);
        if (result.passed) {
          passCount++;
        } else {
          issues.push(result.issue!);
        }
      }

      if (issues.length > 0) {
        console.warn('\n  Character limit violations:');
        for (const issue of issues) {
          console.warn(`    - ${issue}`);
        }
      }

      console.log(`\n  Platform limits: ${passCount}/${platformAssets.length} passed`);

      // Most platform-specific assets should respect limits
      if (platformAssets.length > 0) {
        expect(passCount / platformAssets.length).toBeGreaterThanOrEqual(0.75);
      }
    });
  });

  // ─── Individual Asset Deep Checks ──────────────────────────────────
  describe('Deep Check: Individual Asset Types', () => {
    it('show_notes should contain markdown formatting and episode topics', () => {
      const showNotes = assets.find(a => a.asset_type === 'show_notes');
      if (!showNotes) return; // Skip if not generated

      expect(showNotes.content.length).toBeGreaterThan(100);

      // Should have markdown formatting
      const hasMarkdown = showNotes.content.includes('#') ||
        showNotes.content.includes('**') ||
        showNotes.content.includes('- ');
      expect(hasMarkdown).toBe(true);
    });

    it('key_takeaways should list distinct items', () => {
      const takeaways = assets.find(a => a.asset_type === 'key_takeaways');
      if (!takeaways) return;

      expect(takeaways.content.length).toBeGreaterThan(50);
    });

    it('blog_post should be substantial long-form content', () => {
      const blog = assets.find(a => a.asset_type === 'blog_post');
      if (!blog) return;

      expect(blog.content.length).toBeGreaterThan(300);

      // Should have markdown structure
      const hasStructure = blog.content.includes('#') || blog.content.includes('**');
      expect(hasStructure).toBe(true);
    });

    it('linkedin_post should be professional and within platform limits', () => {
      const linkedin = assets.find(a => a.asset_type === 'linkedin_post');
      if (!linkedin) return;

      expect(linkedin.content.length).toBeGreaterThan(50);
      expect(linkedin.content.length).toBeLessThanOrEqual(3000);
    });

    it('twitter_thread should have multiple tweets within 280 chars each', () => {
      const thread = assets.find(a => a.asset_type === 'twitter_thread');
      if (!thread) return;

      try {
        const parsed = JSON.parse(thread.content);
        if (Array.isArray(parsed)) {
          expect(parsed.length).toBeGreaterThanOrEqual(3);
          for (const tweet of parsed) {
            const text = typeof tweet === 'string' ? tweet : tweet?.text;
            if (typeof text === 'string') {
              expect(text.length).toBeLessThanOrEqual(280);
            }
          }
        }
      } catch {
        // Not JSON — just verify it has reasonable content
        expect(thread.content.length).toBeGreaterThan(100);
      }
    });

    it('seo_description should be concise and keyword-rich', () => {
      const seo = assets.find(a => a.asset_type === 'seo_description');
      if (!seo) return;

      expect(seo.content.length).toBeGreaterThanOrEqual(50);
      expect(seo.content.length).toBeLessThanOrEqual(3000); // Full SEO package, not just meta
    });

    it('guest_bio_short should reference the guest', () => {
      const bio = assets.find(a => a.asset_type === 'guest_bio_short');
      if (!bio || !guestName) return;

      expect(bio.content.length).toBeGreaterThan(30);
    });

    it('transcript_summary should capture main discussion points', () => {
      const summary = assets.find(a => a.asset_type === 'transcript_summary');
      if (!summary) return;

      expect(summary.content.length).toBeGreaterThan(50);

      // Summary should have keyword overlap with the transcript
      const relevance = assertContentRelevance(summary.content, transcript, 3);
      expect(relevance.passed).toBe(true);
    });
  });
});
