import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service for PodBrain, the AI-powered podcast content platform.',
}

export default function TermsOfServicePage() {
  return (
    <article>
      <h1 className="font-display text-3xl font-bold tracking-tight text-foreground mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-muted-foreground mb-10">
        Last updated: February 26, 2026
      </p>

      <div className="space-y-8 text-muted-foreground leading-relaxed">
        {/* 1 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using PodBrain (&quot;the Service&quot;), operated at
            getpodbrain.ai, you agree to be bound by these Terms of Service
            (&quot;Terms&quot;). If you do not agree to all of these Terms, you
            may not access or use the Service. We reserve the right to update
            these Terms at any time. Continued use of the Service after changes
            are posted constitutes acceptance of the revised Terms. We will make
            reasonable efforts to notify you of material changes via the email
            address associated with your account.
          </p>
        </section>

        {/* 2 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            2. Description of Service
          </h2>
          <p>
            PodBrain is an AI-powered platform for podcasters that transforms
            audio recordings into SEO-optimized show notes, content assets, and
            guest promotion packages. The Service includes audio transcription
            (powered by third-party providers), AI-driven content generation,
            custom vocabulary learning, SEO analysis, and related tools designed
            to help podcasters create and distribute content more efficiently.
          </p>
          <p className="mt-3">
            The Service is provided on an &quot;as-is&quot; and
            &quot;as-available&quot; basis. We continuously improve and update
            the Service, which may include adding, modifying, or removing
            features at any time without prior notice.
          </p>
        </section>

        {/* 3 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            3. User Accounts
          </h2>
          <p>
            To use certain features of the Service, you must create an account.
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account. You agree to provide accurate, current, and complete
            information during registration and to update such information as
            needed to keep it accurate.
          </p>
          <p className="mt-3">
            You must notify us immediately of any unauthorized use of your
            account or any other breach of security. PodBrain will not be liable
            for any loss or damage arising from your failure to protect your
            account credentials.
          </p>
        </section>

        {/* 4 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            4. Acceptable Use
          </h2>
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc list-inside mt-3 space-y-1.5">
            <li>
              Upload, transmit, or distribute content that is unlawful,
              defamatory, obscene, or infringes on the intellectual property
              rights of others.
            </li>
            <li>
              Attempt to gain unauthorized access to the Service, other user
              accounts, or any computer systems or networks connected to the
              Service.
            </li>
            <li>
              Use the Service for any purpose that is fraudulent, deceptive, or
              harmful to others.
            </li>
            <li>
              Interfere with, disrupt, or create an undue burden on the Service
              or the networks or servers connected to the Service.
            </li>
            <li>
              Use automated means (bots, scrapers, or similar technology) to
              access the Service except through APIs we explicitly provide.
            </li>
            <li>
              Resell, sublicense, or redistribute the Service or any output
              generated by the Service in a manner that competes directly with
              PodBrain.
            </li>
          </ul>
          <p className="mt-3">
            We reserve the right to suspend or terminate your account if we
            determine, in our sole discretion, that you have violated these
            Terms.
          </p>
        </section>

        {/* 5 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            5. Intellectual Property
          </h2>
          <p>
            <strong className="text-foreground">Your Content.</strong> You retain
            full ownership of all audio files, transcripts, and other content you
            upload to the Service (&quot;Your Content&quot;). By uploading
            content, you grant PodBrain a limited, non-exclusive, worldwide
            license to process, store, and analyze Your Content solely for the
            purpose of providing and improving the Service. This license
            terminates when you delete Your Content or close your account.
          </p>
          <p className="mt-3">
            <strong className="text-foreground">Generated Content.</strong>{' '}
            Content generated by the Service based on Your Content (such as show
            notes, summaries, social media posts, and SEO analysis) is owned by
            you. You are free to use, modify, publish, and distribute generated
            content without restriction.
          </p>
          <p className="mt-3">
            <strong className="text-foreground">PodBrain IP.</strong> The
            Service, including its design, software, algorithms, branding,
            documentation, and all related intellectual property, remains the
            exclusive property of PodBrain. Nothing in these Terms grants you any
            right, title, or interest in the Service beyond the limited right to
            use it in accordance with these Terms.
          </p>
        </section>

        {/* 6 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            6. Payment Terms
          </h2>
          <p>
            PodBrain offers both free and paid subscription plans. Paid plans are
            billed on a monthly or annual basis through our payment processor,
            Stripe. By subscribing to a paid plan, you authorize us to charge
            your payment method on a recurring basis until you cancel.
          </p>
          <p className="mt-3">
            All fees are stated in US dollars and are non-refundable except where
            required by applicable law. We reserve the right to change pricing
            at any time, but will provide at least 30 days&apos; advance notice
            of price increases to existing subscribers. The new pricing will
            take effect at the start of your next billing cycle following the
            notice period.
          </p>
          <p className="mt-3">
            If payment fails, we may suspend access to paid features until the
            balance is settled. We will make reasonable efforts to notify you
            before suspension.
          </p>
        </section>

        {/* 7 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            7. Termination
          </h2>
          <p>
            You may terminate your account at any time by contacting us or using
            the account settings within the Service. Upon termination, your right
            to use the Service will immediately cease, and we will delete your
            stored data within 30 days unless retention is required by law.
          </p>
          <p className="mt-3">
            We may suspend or terminate your access to the Service at any time,
            with or without cause, and with or without notice. Reasons for
            termination may include, but are not limited to, violation of these
            Terms, non-payment, or extended inactivity.
          </p>
        </section>

        {/* 8 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            8. Disclaimers
          </h2>
          <p>
            The Service is provided &quot;as is&quot; and &quot;as
            available&quot; without warranties of any kind, whether express or
            implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and
            non-infringement.
          </p>
          <p className="mt-3">
            PodBrain does not guarantee the accuracy, completeness, or
            reliability of any content generated by the Service&apos;s AI
            features. AI-generated content, including transcriptions, show notes,
            and SEO recommendations, may contain errors. You are responsible for
            reviewing and editing all generated content before publication.
          </p>
        </section>

        {/* 9 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            9. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, PodBrain and its
            officers, directors, employees, and agents shall not be liable for
            any indirect, incidental, special, consequential, or punitive
            damages, or any loss of profits, revenue, data, or use, arising out
            of or related to your use of the Service, whether based on warranty,
            contract, tort, or any other legal theory.
          </p>
          <p className="mt-3">
            In no event shall PodBrain&apos;s total aggregate liability exceed
            the amount you have paid to PodBrain in the twelve (12) months
            preceding the claim, or one hundred US dollars ($100), whichever is
            greater.
          </p>
        </section>

        {/* 10 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            10. Indemnification
          </h2>
          <p>
            You agree to indemnify, defend, and hold harmless PodBrain and its
            officers, directors, employees, and agents from and against any
            claims, liabilities, damages, losses, and expenses (including
            reasonable legal fees) arising out of or in any way connected with
            your access to or use of the Service, your violation of these Terms,
            or your infringement of any intellectual property or other rights of
            any third party.
          </p>
        </section>

        {/* 11 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            11. Governing Law
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with the
            laws of the State of Delaware, United States, without regard to its
            conflict of law provisions. Any disputes arising under or in
            connection with these Terms shall be subject to the exclusive
            jurisdiction of the courts located in the State of Delaware.
          </p>
        </section>

        {/* 12 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            12. Severability
          </h2>
          <p>
            If any provision of these Terms is held to be invalid or
            unenforceable, the remaining provisions shall continue in full force
            and effect. The invalid or unenforceable provision will be deemed
            modified to the minimum extent necessary to make it valid and
            enforceable.
          </p>
        </section>

        {/* 13 */}
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground mb-3">
            13. Contact
          </h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <p className="mt-3">
            <strong className="text-foreground">Email:</strong>{' '}
            <a
              href="mailto:legal@getpodbrain.ai"
              className="text-accent underline underline-offset-2 hover:text-accent/80 transition-colors"
            >
              legal@getpodbrain.ai
            </a>
          </p>
        </section>
      </div>
    </article>
  )
}
