/**
 * Independent Asset Quality Verification
 *
 * Uses a DIFFERENT AI model (Claude via Anthropic API) to evaluate the
 * quality of assets generated by Grok. This eliminates the bias of
 * having the same model grade its own work.
 *
 * Run:
 *   ANTHROPIC_API_KEY=sk-ant-... npx tsx test/quality/verify-assets.ts <episodeId>
 *
 * Or without an Anthropic key, run programmatic-only checks:
 *   npx tsx test/quality/verify-assets.ts <episodeId> --no-ai
 *
 * What it checks:
 *   Programmatic (always):
 *   - Character length within platform limits
 *   - Keyword overlap with transcript (relevance)
 *   - No hallucination markers (Stoicism content, wrong guest names)
 *   - Structural validity (markdown headers, tweet count, etc.)
 *
 *   AI-judged (when ANTHROPIC_API_KEY is set):
 *   - Content accuracy vs transcript
 *   - Tone appropriateness for the platform
 *   - Actionability and shareability
 *   - Overall quality score 1-10
 */
import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'
config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
)

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY
const USE_AI = ANTHROPIC_API_KEY && !process.argv.includes('--no-ai')
const EPISODE_ID = process.argv[2]

if (!EPISODE_ID) {
  console.error('Usage: npx tsx test/quality/verify-assets.ts <episodeId> [--no-ai]')
  process.exit(1)
}

// Platform-specific constraints
const PLATFORM_LIMITS: Record<string, { minLen: number; maxLen: number; structural?: (c: string) => string | null }> = {
  twitter_thread: {
    minLen: 500,
    maxLen: 5000,
    structural: (c) => {
      const tweetCount = (c.match(/^\d+[./)\s]/gm) || []).length
      return tweetCount >= 4 ? null : `Expected 6-10 numbered tweets, found ${tweetCount}`
    },
  },
  linkedin_post: { minLen: 400, maxLen: 3500 },
  blog_post: {
    minLen: 3000,
    maxLen: 15000,
    structural: (c) => {
      const headers = (c.match(/^#{1,3}\s/gm) || []).length
      return headers >= 2 ? null : `Expected 3+ headers, found ${headers}`
    },
  },
  newsletter_email: { minLen: 500, maxLen: 5000 },
  key_takeaways: {
    minLen: 200,
    maxLen: 3000,
    structural: (c) => {
      const bullets = (c.match(/^[-*\d][\s.)/]/gm) || []).length
      return bullets >= 3 ? null : `Expected 5+ takeaway bullets, found ${bullets}`
    },
  },
  ai_summary_short: { minLen: 50, maxLen: 200 },
  seo_description: { minLen: 100, maxLen: 600 },
  chapter_markers: {
    minLen: 100,
    maxLen: 2000,
    structural: (c) => {
      const timestamps = (c.match(/\d{1,2}:\d{2}/g) || []).length
      return timestamps >= 4 ? null : `Expected 6+ timestamps, found ${timestamps}`
    },
  },
  instagram_caption: { minLen: 200, maxLen: 5000 },
  youtube_description: { minLen: 500, maxLen: 5500 },
  guest_bio_short: { minLen: 100, maxLen: 3000 },
  guest_promo_kit: { minLen: 200, maxLen: 6000 },
}

// Hallucination markers — these should NEVER appear in real content
const HALLUCINATION_MARKERS = [
  /\bstoic\b/i,
  /marcus aurelius/i,
  /\bmeditations\b/i,
  /daily stoic/i,
  /ryan holiday/i,
]

interface CheckResult {
  check: string
  pass: boolean
  detail: string
}

interface AssetReport {
  type: string
  checks: CheckResult[]
  aiScore?: number
  aiNotes?: string
}

async function callClaude(prompt: string): Promise<string> {
  if (!ANTHROPIC_API_KEY) return ''
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 500,
      messages: [{ role: 'user', content: prompt }],
    }),
  })
  const data = await res.json()
  return data.content?.[0]?.text || ''
}

async function verifyAsset(
  asset: { asset_type: string; content: string },
  transcript: string,
  guestName: string
): Promise<AssetReport> {
  const checks: CheckResult[] = []
  const spec = PLATFORM_LIMITS[asset.asset_type]
  const content = asset.content || ''

  // 1. Length check
  if (spec) {
    const lenOk = content.length >= spec.minLen && content.length <= spec.maxLen
    checks.push({
      check: 'Length',
      pass: lenOk,
      detail: `${content.length} chars (expected ${spec.minLen}-${spec.maxLen})`,
    })
  }

  // 2. Structural check
  if (spec?.structural) {
    const issue = spec.structural(content)
    checks.push({
      check: 'Structure',
      pass: !issue,
      detail: issue || 'Valid structure',
    })
  }

  // 3. Keyword relevance (at least 3 transcript keywords in the asset)
  const transcriptWords = transcript
    .toLowerCase()
    .split(/\s+/)
    .filter((w) => w.length > 5)
  const wordFreq = new Map<string, number>()
  for (const w of transcriptWords) {
    wordFreq.set(w, (wordFreq.get(w) || 0) + 1)
  }
  const topKeywords = [...wordFreq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([word]) => word)

  const contentLower = content.toLowerCase()
  const keywordHits = topKeywords.filter((kw) => contentLower.includes(kw))
  checks.push({
    check: 'Keyword relevance',
    pass: keywordHits.length >= 3,
    detail: `${keywordHits.length}/20 top transcript keywords found: ${keywordHits.slice(0, 5).join(', ')}`,
  })

  // 4. Guest name mention (where applicable)
  if (['guest_bio_short', 'guest_promo_kit', 'linkedin_post', 'blog_post'].includes(asset.asset_type)) {
    const mentionsGuest = contentLower.includes(guestName.toLowerCase().split(' ')[1]?.toLowerCase() || '')
    checks.push({
      check: 'Guest mention',
      pass: mentionsGuest,
      detail: mentionsGuest ? `Mentions ${guestName}` : `Missing guest name "${guestName}"`,
    })
  }

  // 5. No hallucination
  const hallucinationHits = HALLUCINATION_MARKERS.filter((rx) => rx.test(content))
  checks.push({
    check: 'No hallucination',
    pass: hallucinationHits.length === 0,
    detail:
      hallucinationHits.length === 0
        ? 'Clean'
        : `HALLUCINATION: matched ${hallucinationHits.map((r) => r.source).join(', ')}`,
  })

  // 6. AI-judged quality (Claude, independent from Grok)
  let aiScore: number | undefined
  let aiNotes: string | undefined

  if (USE_AI) {
    try {
      const aiResponse = await callClaude(
        `You are evaluating a podcast content asset for quality. Score it 1-10 and provide 1-2 sentences of feedback.

Asset type: ${asset.asset_type}
Guest: ${guestName}

Asset content:
${content.slice(0, 2000)}

Transcript excerpt (for accuracy check):
${transcript.slice(0, 1500)}

Respond ONLY in this format:
SCORE: N
NOTES: your feedback here`
      )
      const scoreMatch = aiResponse.match(/SCORE:\s*(\d+)/)
      const notesMatch = aiResponse.match(/NOTES:\s*(.+)/s)
      aiScore = scoreMatch ? parseInt(scoreMatch[1], 10) : undefined
      aiNotes = notesMatch ? notesMatch[1].trim() : aiResponse
    } catch {
      aiNotes = 'AI verification unavailable'
    }
  }

  return { type: asset.asset_type, checks, aiScore, aiNotes }
}

async function main() {
  console.log('╔══════════════════════════════════════════════════════════╗')
  console.log('║  INDEPENDENT QUALITY VERIFICATION' + (USE_AI ? ' (Claude-judged)' : ' (programmatic only)') + '  ║')
  console.log('╚══════════════════════════════════════════════════════════╝')
  console.log('')

  // Fetch episode + assets
  const { data: ep } = await supabase
    .from('episodes')
    .select('*')
    .eq('id', EPISODE_ID)
    .single()

  if (!ep) {
    console.error('Episode not found: ' + EPISODE_ID)
    process.exit(1)
  }

  const { data: assets } = await supabase
    .from('generated_assets')
    .select('*')
    .eq('episode_id', EPISODE_ID)
    .order('created_at')

  if (!assets?.length) {
    console.error('No assets found for episode ' + EPISODE_ID)
    process.exit(1)
  }

  console.log(`Episode: ${ep.title}`)
  console.log(`Guest: ${ep.guest_name}`)
  console.log(`Assets: ${assets.length}`)
  console.log(`Verification: ${USE_AI ? 'Claude AI + Programmatic' : 'Programmatic only'}`)
  console.log('')

  // Verify each asset
  const reports: AssetReport[] = []
  for (const asset of assets) {
    process.stdout.write(`Verifying ${asset.asset_type}... `)
    const report = await verifyAsset(
      asset,
      ep.transcript || '',
      ep.guest_name || 'Unknown'
    )
    reports.push(report)

    const allPass = report.checks.every((c) => c.pass)
    const icon = allPass ? '✅' : '⚠️'
    const score = report.aiScore ? ` [AI: ${report.aiScore}/10]` : ''
    console.log(`${icon}${score}`)

    if (!allPass) {
      for (const c of report.checks.filter((ch) => !ch.pass)) {
        console.log(`    ❌ ${c.check}: ${c.detail}`)
      }
    }
    if (report.aiNotes) {
      console.log(`    📝 ${report.aiNotes}`)
    }
  }

  // Summary
  console.log('')
  const totalChecks = reports.flatMap((r) => r.checks)
  const passed = totalChecks.filter((c) => c.pass).length
  const failed = totalChecks.filter((c) => !c.pass).length
  const avgAiScore =
    reports.filter((r) => r.aiScore).reduce((sum, r) => sum + (r.aiScore || 0), 0) /
      Math.max(1, reports.filter((r) => r.aiScore).length) || 0

  console.log('╔══════════════════════════════════════════════════╗')
  console.log(`║  Checks: ${passed} passed / ${failed} failed / ${totalChecks.length} total`)
  if (USE_AI) {
    console.log(`║  AI avg score: ${avgAiScore.toFixed(1)}/10`)
  }
  console.log(`║  Assets verified: ${reports.length}`)
  console.log(`║  Hallucinations: ${totalChecks.filter((c) => c.check === 'No hallucination' && !c.pass).length === 0 ? 'NONE ✅' : 'DETECTED ❌'}`)
  console.log('╚══════════════════════════════════════════════════╝')
}

main().catch(console.error)
